RSpec:
  Language:
    ExampleGroups:
      Regular:
        - path
        - response
        - get
        - post
        - patch
        - put
        - delete
        - head
        - options
        - trace
    Examples:
      Regular:
        - run_test!

RSpec/NestedGroups:
  AllowedGroups:
    - path
    - response
    - get
    - post
    - patch
    - put
    - delete
    - head
    - options
    - trace
